version: '3.1'
services:
  my-service:
    image: my-service:latest
    ports:
      - "8080:8080"
    links:
      - "db:db-host"
    restart: unless-stopped
  db:
    image: bitnami/cassandra:latest
    expose:
      - "9042"
